##### 集群节点3配置
spring:
  application:
    name: eureka-server
  profiles:
    active: cluster1
server:
  port: 8763

eureka:
  instance:
    # 该实例在集群中的唯一标识
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    # 使用IP注册
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ipAddress}
    # 心跳间隔（单位：s）
    lease-renewal-interval-in-seconds: 3
    # 服务失效时间（如果多久没有收到心跳，则可以删除服务）
    lease-expiration-duration-in-seconds: 7
    hostname: cluster3

  client:
    # 关闭eureka client
    # enabled: false
    # 是否注册自身到eureka服务器
    registerWithEureka: true
    # 是否从eureka服务器获取注册信息
    fetchRegistry: true
    # 客户端从Eureka Server集群里更新Eureka Server信息的间隔（单位：s）
    eureka-service-url-poll-interval-seconds: 60
    # 客户端从注册中心获取注册服务的信息的间隔
    registry-fetch-interval-seconds: 5
    # 设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址，可同时指定多个
    serviceUrl:
      defaultZone: http://cluster1:8761/eureka/,http://cluster2:8762/eureka/
  server:
    # 关闭自我保护机制
    enable-self-preservation: false
    # 自我保护系数，当enable-self-preservation=true时启用
    # renewal-percent-threshold: 0.1
    # 设置清理间隔,单位为毫秒,默认为0
    eviction-interval-timer-in-ms: 3000
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务（单位：ms）
    wait-time-in-ms-when-sync-empty: 6000000
    # 集群之间相互更新节点信息的时间频率（单位：ms）
    peer-eureka-nodes-update-interval-ms: 60000