server:
  port: 7900
spring:
  application:
    name: module-service-provider
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG



# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://10.201.169.147:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    #访问路径可以显示IP地址
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ipAddress}