spring:
  application:
    name: gateway-zuul
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    # 采样策略
    sampler:
      # 采样比例（0.0-1.0之间）
      percentage: 1.0

server:
  port: 7777

#### 网关路由相关配置
zuul:
  routes:
    producer:
      path: /producer/**
      # 服务注册中心的服务名
      serviceId: MODULE-SERVICE-PROVIDER
      # 移除前缀
      stripPrefix: true
      # 不过滤Cookie, Set-Cookie, Authorization
      customSensitiveHeaders: true

  # 是否开启debug日志
  debug:
    request: true
  include-debug-header: true

  # 是否开启路由重试
  retryable: true

#### 负载均衡相关配置
ribbon:
  # 连接超时时间(ms)
  ConnectTimeout: 1000
  # 通信超时时间(ms)
  ReadTimeout: 2000
  # 是否对所有操作重试
  OkToRetryOnAllOperations: true
  # 同一服务不同实例的重试次数
  MaxAutoRetriesNextServer: 1
  # 同一实例的重试次数（默认为0）
  MaxAutoRetries: 0
  ### ribbonTimeout = (ReadTimeout + ConnectTimeout) * (MaxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);

#### 熔断机制相关配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断超时时长，需要大于ribbonTimeout (ms)
            timeoutInMillisecond: 60000

#### 注册中心相关配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    #访问路径可以显示IP地址
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ipAddress}
